# Active Enrollment
volleyball_active_enrollment_organization:
    path: /active-enrollment/organization/{organization}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:organization, organization: null }
volleyball_active_enrollment_council:
    path: /active-enrollment/council/{council}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:council, council: null }
volleyball_active_enrollment_region:
    path: /active-enrollment/region/{region}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:region, region: null }
volleyball_active_enrollment_passel:
    path: /active-enrollment/passel/{passel}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:passel, passel: null }
volleyball_active_enrollment_facility:
    path: /active-enrollment/facility/{facility}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:facility, facility: null }
volleyball_active_enrollment_season:
    path: /active-enrollment/season/{season}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:season, season: null }
volleyball_active_enrollment_week:
    path: /active-enrollment/week/{week}
    defaults: { _controller: VolleyballEnrollmentBundle:ActiveEnrollment:week, week: null }
        