# AttendeeClassEnrollment
volleyball_attendee_class_enrollment_index:
    path: /attendee/{attendee_slug}/class-enrollments
    methods: [GET]
    defaults:
        _controller: volleyball.controller.attendee_class_enrollment:indexAction
volleyball_attendee_class_enrollment_show:
    path: /attendee/{attendee_slug}/class-enrollments/{attendee_class_enrollment_slug}
    methods: [GET]
    defaults:
        _controller: volleyball.controller.attendee_class_enrollment:showAction
volleyball_attendee_class_enrollment_new:
    path: /attendee/{attendee_slug}/class-enrollments/new
    methods: [GET, POST]
    defaults:
        _controller: volleyball.controller.attendee_class_enrollment:newAction