# PasselEnrollment
volleyball_passel_enrollment_index:
    path: /passels/{passel_slug}/enrollments
    methods: [GET]
    defaults:
        _controller: volleyball.controller.passel_enrollment:indexAction
volleyball_passel_enrollment_show:
    path: /passels/{passel_slug}/enrollments/{passel_enrollment_slug}
    methods: [GET]
    defaults:
        _controller: volleyball.controller.passel_enrollment:showAction
volleyball_passel_enrollment_new:
    path: /passels/{passel_slug}/enrollments/new
    methods: [GET, POST]
    defaults:
        _controller: volleyball.controller.passel_enrollment:newAction