# Period
volleyball_period_index:
    path: /periods
    methods: [GET]
    defaults:
        _controller: volleyball.controller.period:indexAction
volleyball_period_show:
    path: /periods/{period_slug}
    methods: [GET]
    defaults:
        _controller: volleyball.controller.period:showAction
volleyball_period_new:
    path: /periods/new
    methods: [GET, POST]
    defaults:
        _controller: volleyball.controller.period:newAction
volleyball_period_index_by_week:
    path: /weeks/{week_slug}/periods
    methods: [GET]
    defaults:
        _controller: volleyball.controller.period:indexAction