# Season
volleyball_season_index:
    path: /seasons
    methods: [GET]
    defaults:
        _controller: volleyball.controller.season:indexAction
        _sylius:
            sorting:
                score: desc
            template: VolleyballResourceBundle:Season:index.html.twig
volleyball_season_show:
    path: /seasons/{season_slug}
    methods: [GET]
    defaults:
        _controller: volleyball.controller.season.showAction
        _sylius:
            template: VolleyballResourceBundle:Season:show.html.twig
volleyball_season_new:
    path: /seasons/new
    methods: [GET, POST]
    defaults:
        _controller: volleyball.controller.season.newAction
        _sylius:
            template: VolleyballResourceBundle:Season:new.html.twig
volleyball_season_index_by_facility:
    path: /facilities/{facility_slug}/seasons
    methods: [GET]
    defaults:
        _controller: VolleyballEnrollmentBundle:Season:indexAction
        